### ISSUE TITLE
Support: British Summer Time

### ISSUE THREAD

**Issue by joereddington** [collective/icalendar#230]
So I'm creating events like this: 

```
  4 def add_event(cal, summary, start, end):
  3         event = Event()
  2         event.add('summary', summary)
  1         event.add('dtstart', start)
  0         event.add('dtend', end)
  1         event.add('dtstamp', end)
  2         event['uid'] = summary+str(start)+str(end)
  3         event.add('priority', 5)
  4 
  5         cal.add_component(event)
```
and producing [this](http://flow.joereddington.com/watson/calendars/projects.ics) calendar file.   However, for some reason the Google things that the times are all in GMT - which means that evnts that take place in British Summer Time, are shown an hour out.  In fact, all my times a 'local' so some are in GMT and some are in BST depending on what the date is.  What's the best way of handling this?

**Comment by geier** [comment]
This isn't a great example, because it doesn't show what kind of starts
and ends you are inserting. From the output you post I'm pretty sure
they are not localized, but floating.

If you do something like this:

```
LONDON = pytz.timezone('Europe/London')
event.add('dtstart', LONDON.localize(dt.datetime.now()))
```
you should end up with something that looks like this:

```
DTSTART;TZID=Europe/London;VALUE=DATE-TIME:20170531TXXYYZZ .
```

BUT.... icalendar does not actually create VTIMEZONE components for you,
you'll have to do that for yourself. If you really need to do this, you
might want to have a look at https://github.com/pimutils/khal 's code
base and see how we do it there (grep for VTIMEZONE).

If you are lucky, google might actually interpret a
TZID=$olsondb_identifier as you intended, but it might also discard that
completely.

Unrelated note: you should set DTSTAMP to the current time, not the end
of the event.

Quoting Joe Reddington (2017-05-31 17:14:14)

**Comment by joereddington** [comment]
Awesome! Thank you :)
