### ISSUE TITLE
Docs site is down? 

### ISSUE THREAD

**Issue by davidawad** [collective/icalendar#288]
https://icalendar.readthedocs.io/en/latest/ 

It would seem that the docs website isn't loading CSS anymore because of a bad cert :(

**Comment by Lx** [comment]
Duplicate of #270.

For anyone wanting to view the docs properly, a workaround is to try to visit one of the affected resources directly:

https://cdnmedia.readthedocs.org/css/sphinx_rtd_theme.css

and "trust" or otherwise "authorise" that resource to be visited.  After this, the docs display correctly.

**Comment by RagingRoosevelt** [comment]
Duplicate of #264

**Comment by davidawad** [comment]
Well I'm glad to hear that the issue has been reported twice before and still exists  😂
