### ISSUE TITLE
Ignore X-... properties also at end of file?

### ISSUE THREAD

**Issue by mmoole** [collective/icalendar#350]
Dear icalendar team,

there is a simple caching mechanism built into the site and thus cached copies of the .ics have a string attached pointing to this at the very end of the file. It looks like this:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Podio API//EN//view-exporter//52593453
METHOD:REQUEST
X-WR-CALNAME:view52593586
X-WR-TIMEZONE:Europe/Berlin
CALSCALE:GREGORIAN
X-COMMENT-USAGE:This calendar does not contain recurring events!
X-COMMENT-GENERATOR:PHP Version 8.0.16 
BEGIN:VEVENT
STATUS:CONFIRMED
SEQUENCE:0
TRANSP:OPAQUE
CLASS:PUBLIC
UID:20055546456446
SUMMARY:Termin 4353 und"so"
DESCRIPTION;ALTREP="data:text/html,%3Cbody%3E%3Cp%3EToller%20%3Cstron
	g%20class%3D%22text-bold%22%3ETermin%3C%2Fstrong%3E%20f%C3%BCr%3C%2Fp
	%3E%3Cblockquote%3E%3Cp%3Emal%20%3Cem%20class%3D%22text-italic%22%3Ez
	u%22gucken%22%3C%2Fem%3E%3C%2Fp%3E%3C%2Fblockquote%3E%3Cp%3E%3Cu%20cl
	ass%3D%22text-underline%22%3Eund%3C%2Fu%3E%20%3Cdel%3Eso%3C%2Fdel%3E%
	3Cbr%2F%3E%3C%2Fp%3E%3C%2Fbody%3E":Toller Termin fürmal zu\"gucken\"
	und so
X-ALT-DESC;FMTTYPE=text/html:<html><head></head><body><p>Toller <stro
	ng class="text-bold">Termin</strong> für</p><blockquote><p>mal <em c
	lass="text-italic">zu"gucken"</em></p></blockquote><p><u class="text-
	underline">und</u> <del>so</del><br/></p></body></html>
URL:https://podio.com/xxxxxxyyyyyy/zpodio-testgelande/apps/calen
	dar/items/5
LOCATION:online
DTSTART:20220222T183000Z
DTEND:20220222T193000Z
DTSTAMP:20220220T142821Z
END:VEVENT
END:VCALENDAR
X-COMMENT:Cached from 2022-02-20 14:28:21 - new at most every 1800sec.
```

Now icalendar is showing this error: `Property "X-COMMENT" does not have a parent component.`
But the file validates fine at https://icalendar.org/validator.html and on the other hand properties beginning with X- may be ignored nevertheless.

So this is to suggest ignoring properties beginning with X- at least for the check if they are within a parent component. Would that be possible?

**Comment by angatha** [comment]
I didn't read RFC5545 complete but I'm sure that the content of an .ics file can only be an [icalstream](https://www.rfc-editor.org/rfc/rfc5545#section-3.4). This allows for one or more VCANELDAR components but nothing else. So the file is actually invalid and therefore, the error is expected. The part about ignoring unknown X- and IANA-registered properties, (components and parameters) doesn't apply in this case, for that reason.

@mmoole can you please provide the code snipped that you used to parse this?
Maybe it is possible instead of raising an exception to store the exception in the errors list? Depending on the used method (e.g. `Calendar.from_ical()`) determine the "correct" object may be difficult when `multiple=True`.

**Comment by yeshwantthota** [comment]
Hey, I am a beginner in open source and want to contribute to this project. So can anybody guide me on how to make my first contribution.

**Comment by mmoole** [comment]
Hello, I am using [open-web-calendar](https://github.com/niccokunzmann/open-web-calendar) which uses icalendar, so I cannot say exactly where the code snippet would reside 🤷🏼‍♂️

**Comment by niccokunzmann** [comment]
I would say it belongs into icalendar since this reads the data and parses it also because it is a valid calendar file that icalendar does not like.

**Comment by mmoole** [comment]
Wonderful 🚀
