### ISSUE TITLE
ignores VTIMEZONE

### ISSUE THREAD

**Issue by rosskarchner** [collective/icalendar#44]
If an iCal file has something like:    (this is from Outlook 2010)

```
BEGIN:VTIMEZONE
TZID:Eastern Standard Time
BEGIN:STANDARD
DTSTART:16011104T020000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010311T020000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
END:VTIMEZONE
```

individual events are supposed to be able to reference it by name, by TZID:

```
DTSTART;TZID="Eastern Standard Time":20120130T100000
```
instead, this package depends entirely on pytz for timezone lookup, ignoring timezones that are defined in the file.

**Comment by thet** [comment]
fixed via https://github.com/collective/icalendar/pull/154

**Comment by Lx** [comment]
Please forgive me, but I'm having a really hard time absorbing all of the information across many of the timezone-related issues in this tracker—

Is there now a defined way to get a VTIMEZONE component from a `timezone`/`tzinfo` object?

I'm creating a number of events in the `Australia/Melbourne` timezone, which are currently not working as expected in Google Calendar (they're displaying as UTC+20 instead of UTC+10) and I believe it's because I'm not including an `Australia/Melbourne` `VTIMEZONE` component in my generated iCalendar file.  However, there's no obvious way from the docs/the code/the discussions here to obtain this.

Please let me know if I should raise this as a new issue.

**Comment by VirginiaDooley** [comment]
Bumpi

> Please forgive me, but I'm having a really hard time absorbing all of the information across many of the timezone-related issues in this tracker—
> 
> Is there now a defined way to get a VTIMEZONE component from a `timezone`/`tzinfo` object?
> 
> I'm creating a number of events in the `Australia/Melbourne` timezone, which are currently not working as expected in Google Calendar (they're displaying as UTC+20 instead of UTC+10) and I believe it's because I'm not including an `Australia/Melbourne` `VTIMEZONE` component in my generated iCalendar file. However, there's no obvious way from the docs/the code/the discussions here to obtain this.
> 
> Please let me know if I should raise this as a new issue.

@Lx did you ever find a solution to this issue? We have the same problem for Europe/London.

**Comment by Lx** [comment]
Sorry, but no.  I ended up abandoning this library altogether and writing the file out manually.
