### ISSUE TITLE
[Security] How to hide email list in ics file or maybe send separate email for each recipient ?

### ISSUE THREAD

**Issue by kev26** [collective/icalendar#506]
With the event including email list recipients in ics file, this is not secure, is there a better way to resolve them? Thank so much.

**Comment by jacadzaca** [comment]
Hi kev, thanks for the interesting question! If I were to solve this problem I would probably only include guests' names in the `attendees` section of the ics and blur out their email addresses, e.g instead of writing `john.doe@example.com` I would make it `j*******@*********`. Please note that this is not ideal, since then people probably (it's dependent on what caldav server you're using) won't be able to accept/refuse the invitation, attendees won't know who's in the meeting with them and won't be able to email them if needed. Sending separate invitation to each recipient also sounds like  a good solution, but share similar issues :) 

I'm closing this issue since it's not really related to the repo per-se -- icalendar is only an ics parser. To solve your problem you probably need to consult your caldav server's/client's manual/mailing list. Feel free to reopen this isuses if you think otherwise, take care :)
