### ISSUE TITLE
Drop claim to support for Python below 3.7

### ISSUE THREAD

**Issue by niccokunzmann** [collective/icalendar#513]
In the README file, we state that we also maintain downwards compatibility:

> [Branch 4.x](https://github.com/collective/icalendar/tree/4.x) with maximum compatibility to Python versions 2.7 and 3.4+, PyPy2 and PyPy3.

It is not actually true from my perspective: We have not received one PR with a fix to that branch. There were [PRs that could have been applied to master and to 4.x](https://github.com/collective/icalendar/pulls?q=is%3Apr+is%3Aclosed+label%3A%22needs+4.x+PR+too%22), too but nobody did it. There is no update except from tests since we took up maintenance again.

So, it would be right from my perspective, to drop the claim.
Here is my proposal:

-----

Since we pour more [ effort into maintaining and developing icalendar](https://github.com/collective/icalendar/discussions/360), we decided on this structure:

-    [Branch master](https://github.com/collective/icalendar/) is compatible to Python versions 3.7+ and PyPy3.
-    [Branch 4.x](https://github.com/collective/icalendar/tree/4.x) with compatibility to Python versions 2.7 and 3.4+, PyPy2 and PyPy3 remains if anyone wishes to [port back fixes](https://github.com/collective/icalendar/pulls?q=is%3Apr+is%3Aclosed+label%3A%22needs+4.x+PR+too%22).

---
What are your thoughts on this?

**Comment by mauritsvanrees** [comment]
Seems good to me.

To take Plone as example: Plone 6.0 is where all the current action is, and 5.2 is in maintenance mode.  If a fix is done in 6.0 and it makes sense to apply the same fix in 5.2, then this is possible, but it requires *someone* to do it.  Usually the original creator of a fix does this, sometimes of their own free will, or because someone explicitly asks them.    Sometimes another person does this.  If it is an obvious fix and it takes less than five minutes to back port it and do a quick check, then it often happens.  But often enough, it is not so simple, and it just does not happen.

**Comment by niccokunzmann** [comment]
If we approach this slowly: Our last Py2.7 release was 2023-09-06. Releases to that branch were made once a year. We might not have a contribution to that branch until 2025. in At the moment and more so in 2025, a lot of software has already migrated, 2.7 is end of life. I think, too that it is safe to remove the claim.

**Comment by niccokunzmann** [comment]
Done in https://github.com/collective/icalendar/pull/647/files#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR169
